config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  devise_for :users
  resources :users, only: [:show, :destroy]
  resources :books do
    resources :reviews, only: [:create, :destroy]
    get 'search' => 'books#search', on: :collection
  end
  resources :shopping_cart_items, only: [:index, :create, :destroy]
  resources :orders, only: [:index, :create, :destroy]

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  before_save :set_keywords

  validates :title, :author, :pub_date, :price, :isbn, :description, presence: true
  validates :title, :author, length: { maximum: 150 }
  validates :isbn, length: { maximum: 12 }, format: { with: /\A[\d\-]+\z/ }
  validates :amazon_id, length: { maximum: 50 }, format: { with: /\A[\dA-Z]+\z/ }
  validates :isbn, :amazon_id, uniqueness: { message: 'is not unique' }
  validates :price, numericality: true

  def self.search(keywords)
    where('keywords LIKE :keywords', keywords: "%#{keywords}%") if keywords.present?
  end

  private

  def set_keywords
    self.keywords = [title, author, isbn, amazon_id].join(' ').strip
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, except: [:index, :search, :show]

  def index
    @books = Book.paginate(
      page: params[:page],
      per_page: per_page).order(created_at: :asc)
  end

  def search
    @books = Book.search(params[:keywords]).paginate(
      page: params[:page],
      per_page: per_page).order(created_at: :asc)
    render :index
  end

  def show
    @reviews = @book.reviews
    @review = Review.new
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    title = @book.title
    @book.destroy
    redirect_to books_path, notice: "Book \"#{title}\" has been deleted"
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(
      :title, :author, :publisher, :pub_date, :description,
      :price, :isbn, :amazon_id)
  end

  def admin_only
    redirect_to_books_page unless current_user.admin?
  end

  def redirect_to_books_page
    redirect_to books_path, flash: { alert: 'Only admin can manage books' }
  end

  def per_page
    5
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_cover(title, amazon_id = nil)
    if amazon_id.nil?
      url = "http://placehold.it/140x172"
    else
      url = "http://images.amazon.com/images/P/#{amazon_id}.01.ZTZZZZZZ.jpg"
    end
    image_tag(url, alt: title)
  end

  def format_pub_date(created_at, show_time = false)
    format = '%B %d, %Y' + (show_time === true ? ' %T' : '')
    Date.parse(created_at.to_s).strftime(format)
  end
end

app/views/books/_add_to_cart.html.haml
- if user_signed_in?
  - if current_user.book_in_shopping_cart?(book)
    .text-center= button_to('Added', '#', disabled: 'disabled', class: 'btn btn-md add-to-cart-btn')
  - else
    .text-center= button_to('Add to cart', shopping_cart_items_path, params: { book_id: book.id }, class: 'btn btn-md btn-primary add-to-cart-btn')

app/views/books/_book.html.haml
- book_url = book_path(book)
.row
  .col-md-2.book-cover
    = link_to book_cover(h(book.title), book.amazon_id), book_url, title: h(book.title)
  .col-md-8.book-info-block
    %h2= link_to h(book.title), book_url, title: h(book.title)
    %h5
      by #{h(book.author)}
    %p
      %span ISBN-10:
      = book.isbn
    %p
      %span Published:
      = format_pub_date(book.pub_date)
    %p
      = sanitize(book.description.truncate_words(50))
  .col-md-2.book-price-block
    %p.price-box.text-center= number_to_currency(book.price)
    = render 'add_to_cart', book: book
%hr/

app/views/books/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    - if @book.errors.any?
      = render 'shared/error', model: @book
    = form_for @book, html: {role: 'form'} do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :author
        = f.text_field :author, class: 'form-control'
      .form-group
        = f.label :pub_date
        = f.date_select :pub_date, class: 'form-control'
      .form-group
        = f.label :price
        = f.text_field :price, class: 'form-control'
      .form-group
        = f.label :isbn, 'ISBN'
        = f.text_field :isbn, class: 'form-control'
      .form-group
        = f.label :amazon_id, 'Amazon id'
        = f.text_field :amazon_id, class: 'form-control'
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control', rows: 8
      .actions
        = f.submit 'Save', class: 'btn btn-lg btn-primary btn-block'

app/views/books/_search.html.haml
.row
  %form.form-inline.search-book-form{:action => search_books_path}
    .form-group.col-md-6
      = text_field_tag(:keywords, params[:keywords], class: 'form-control search-book-title')
    %button.btn.btn-primary{:type => "submit"} Search
    .form-group.col-md-6.book-search-by
      %span Search book by title, author, isbn or amazon id
      = link_to 'Reset', root_url, class: 'radio-inline'

/ .row
/   = form_for '', enforce_utf8: false, html: { method: :get, role: 'form', class: 'form-inline search-book-form' } do |f|
/     .form-group.col-md-6
/       = f.text_field :keywords, class: 'form-control search-book-title'
/     / # = f.submit :Search, class: 'button btn btn-primary'
/     = f.button :Search, class: 'button btn btn-primary', name: ''
/     .form-group.col-md-6.book-search-by
/       %span Search book by title, author, isbn or amazon id
/       = link_to 'Reset', root_url, class: 'radio-inline'

app/views/books/edit.html.haml
.row
  = render 'shared/back_button', link: book_path
%h1.text-center Editing book
%hr/
= render 'form'

app/views/books/index.html.haml
= render 'shared/flash_notice' if notice
= render 'shared/flash_alert' if alert
= render 'search'
.pull-left
.pull-right.book-count-block
  %p.text-info
    = pluralize(@books.count, 'book')
    in the catalog
.clearfix
- if @books.any?
  = will_paginate @books
  = render @books
  = will_paginate @books
-else
  .alert.alert-danger.alert-big.text-center No books found 

app/views/books/new.html.haml
= render 'shared/page_header', title: 'New book'
= render 'form'

app/views/books/show.html.haml
.row
  = render 'shared/back_button', link: books_path
  .clearfix
  = render 'shared/flash_notice' if notice
  .col-md-3.book-cover-lg
    %p.text-center
      = book_cover(h(@book.title), @book.amazon_id)
    - if user_signed_in? && current_user.admin?
      .pull-left
        = link_to 'Edit', edit_book_path(@book), class: 'btn btn-md btn-warning book-edit-link'
      .pull-right
        = button_to 'Delete', @book, method: :delete, data: { confirm: 'Are you sure ?' }, class: 'btn btn-md btn-danger book-delete-link'
  .col-md-7.book-info-block
    %h1= h(@book.title)
    %p
      %strong
        by #{h(@book.author)}
    %p
      %span ISBN-10:
      = @book.isbn
    %p
      %span Published:
      = format_pub_date(@book.pub_date)
    %p= sanitize @book.description, tags: %w(p h5 ul li)
  .col-md-2.book-price-block
    %p.text-center.price-box= number_to_currency(@book.price)
    = render 'add_to_cart', book: @book
.row
  #reviews.col-md-10.col-md-offset-1
    - if @reviews.any?
      %hr/
      %h4.text-center Customer reviews
      = render @reviews
    = render 'reviews/form' if user_signed_in?