config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  devise_for :users
  resources :users, only: [:show, :destroy]
  resources :books do
    resources :reviews, only: [:create, :destroy]
    get 'search' => 'books#search', on: :collection
  end
  resources :shopping_cart_items, only: [:index, :create, :destroy]
  resources :orders, only: [:index, :create, :destroy]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:create, :destroy]
  before_action :build_review, only: [:create]

  def create
    respond_to do |format|
      if @review.save
        format.html { redirect_to book_path(@book), notice: 'New review has been added' }
        format.js   { render layout: false }
      else
        error_message = 'Review could not be saved'
        format.html { redirect_to book_path(@book), flash: { danger: error_message } }
        format.js   { render 'error', layout: false, locals: { message: error_message } }
      end
    end
  end

  def destroy
    respond_to do |format|
      if destroy_review
        format.html { redirect_to book_path(@book), notice: 'Review has been deleted' }
        format.js   { render layout: false }
      else
        error_message = 'Review could not be saved'
        format.html { redirect_to book_path(@book), danger: error_message }
        format.js   { render layout: false, locals: { message: error_message } }
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:text)
  end

  def set_book
    @book = Book.find(params[:book_id])
  end

  def build_review
    @review = @book.reviews.build(review_params)
    @review.user_id = current_user.id
  end

  def destroy_review
    return @book.reviews.destroy(params[:id]) if current_user.admin?
    @book.reviews.where(user_id: current_user).destroy(params[:id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
.add-review-block
  = form_for @review, url: book_reviews_path(@book), remote: true, html: { role: 'form' } do |f|
    .form-group
      = f.label :text, 'Add your review/opinion:'
      = f.text_area :text, class: 'form-control'
    .actions
      = f.submit 'Send', class: 'btn btn-md btn-primary'
%hr/

app/views/reviews/_review.html.haml
.review-block
  - if user_signed_in? && (review.belongs_to_user?(current_user) || current_user.admin?)    
    = link_to(book_review_path(@book, review), method: :delete, data: { confirm: "Are you sure?" }, class: 'pull-right delete-review', title: 'Delete review', remote: true) do
      %span.glyphicon.glyphicon-remove{"aria-hidden" => "true"}
  %p.review-author
    By
    %span.review-user-name= review.user.name
    on #{format_pub_date(review.created_at)}
  %p.review-text= review.text
  %hr/

app/views/reviews/create.js.erb
$("<%= escape_javascript(render @review) %>").insertBefore(".add-review-block");
$('#review_text').val('')
if ($('.review-block').length > 0) {
    $('h4').show()
}

app/views/reviews/destroy.js.erb
$('a[href="<%= j book_review_path(@book, params[:id]) %>"]').parent().remove()
if ($('.review-block').length < 1) {
    $('h4').hide()
}

app/views/reviews/error.js.erb
alert('<%= message %>')