config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  devise_for :users
  resources :users, only: [:show, :destroy]
  resources :books do
    resources :reviews, only: [:create, :destroy]
    get 'search' => 'books#search', on: :collection
  end
  resources :shopping_cart_items, only: [:index, :create, :destroy]
  resources :orders, only: [:index, :create, :destroy]

end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/controllers/shopping_cart_items_controller.rb
class ShoppingCartItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = current_user.shopping_cart_items.joins(:book).order(created_at: :asc)
  end

  def create
    book_title = Book.find(params[:book_id]).title
    if build_shopping_cart_item.save
      redirect_to(
        books_path,
        notice: "\"#{book_title}\" has been added to your shopping cart")
    else
      flash[:danger] = "\"#{book_title}\" could not be added to your shopping cart. Please, try again."
      redirect_to book_path(params[:book_id])
    end
  end

  def destroy
    shopping_cart_item = ShoppingCartItem.find(params[:id])
    if shopping_cart_item.user_id == current_user.id
      shopping_cart_item.destroy
      redirect_to(
        shopping_cart_items_path,
        notice: "\"#{shopping_cart_item.book.title}\" has been removed for the shopping cart")
    else
      redirect_to books_path
    end
  end

  private

  def build_shopping_cart_item
    current_user.shopping_cart_items.build(book_id: params[:book_id])
  end
end

app/helpers/shopping_cart_items_helper.rb
module ShoppingCartItemsHelper
end

app/views/shopping_cart_items/_item.html.haml
- book = cart_item.book
.row
  .col-md-3.book-cover-mini
    = link_to book_cover(h(book.title), book.amazon_id), book_path(book), title: h(book.title)
  .col-md-6
    %h2= link_to h(book.title), book_path(book), title: h(book.title)
    %h5
      by #{h(book.author)} (Author)
    %p
      Publisher: #{h(book.publisher)}
  .col-md-3
    %p.shopping-cart-price-box.text-center= number_to_currency book.price
    .text-center
      / # = button_to('Delete from cart', cart_item, method: :delete, data: { confirm: 'Are you sure ?' }, class: 'btn btn-md btn-danger add-to-cart-btn')
    / # = content_tag(:div, button_to('Delete from cart', cart_item, method: :delete, data: { confirm: 'Are you sure ?' }, class: 'btn btn-md btn-danger add-to-cart-btn'), class: 'text-center')
%hr/

app/views/shopping_cart_items/_shopping_cart_item.html.haml
- book = shopping_cart_item.book
.row
  .col-md-3.book-cover-mini
    = link_to book_cover(h(book.title), book.amazon_id), book_path(book), title: h(book.title)
  .col-md-6
    %h2= link_to h(book.title), book_path(book), title: h(book.title)
    %h5
      by #{h(book.author)} (Author)
  .col-md-3
    %p.shopping-cart-price-box.text-center= number_to_currency book.price
    .text-center
      = button_to('Delete from cart', shopping_cart_item_path(shopping_cart_item), method: :delete, data: { confirm: 'Are you sure ?' }, class: 'btn btn-md btn-danger add-to-cart-btn')
%hr/

app/views/shopping_cart_items/create.html.haml
%h1 ShoppingCartItems#create
%p Find me in app/views/shopping_cart_items/create.html.haml

app/views/shopping_cart_items/destroy.html.haml
%h1 ShoppingCartItems#destroy
%p Find me in app/views/shopping_cart_items/destroy.html.haml

app/views/shopping_cart_items/index.html.haml
= render 'shared/page_header', title: 'Shopping cart'
= render 'shared/flash_alert' if alert
.alert.alert-info.text-center.shopping-cart-info-message{:role => "alert"}
  - if (items_amount = current_user.shopping_cart_items_amount) > 0
    .pull-left= "You have #{pluralize(items_amount, 'item')} in your shopping cart. Total price: <span>#{number_to_currency(current_user.shopping_cart_total_price)}</span>".html_safe
    .pull-right= button_to 'Checkout', orders_path, class: 'btn btn-primary btn-md'
  - else
    %div= 'You do not have any books in your cart yet'
= render 'shared/flash_notice' if notice
.row
  .col-md-8.col-md-offset-2
    = render @items